/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.prog.sample.psv;

import org.junit.Before;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

public class DelimitedValuesToJSONConverterTest {

    DelimitedValuesToJSONConverter converter;

    @Before
    public void before() {
        converter = new DelimitedValuesToJSONConverter();
    }

    @Test(expected = IllegalArgumentException.class)
    public void parseToModelElements_whenEmptyInputThenError() {
        converter.parseToModelElements(null);
    }

    @Test
    public void parseToModelElements_whenOneElementThenReturnOneModelElementInList() {
        String line1 = "value1 | value2 | value3 | value4";
        List<Model> modelList = converter.parseToModelElements(new ByteArrayInputStream(line1.getBytes()));
        assertNotNull(modelList);
        assertEquals(1, modelList.size());
        assertEquals("value1", modelList.get(0).getField1());
        assertEquals("value2", modelList.get(0).getField2());
        assertEquals("value3", modelList.get(0).getField3());
        assertEquals("value4", modelList.get(0).getField4());
    }

    @Test
    public void parseToModelElements_whenTwoElementThenReturnTwoModelElementInList() {
        String lines = "value1 | value2 | value3 | value4\n"
                + "value1 | value2 | value3 | value4";
        List<Model> modelList = converter.parseToModelElements(new ByteArrayInputStream(lines.getBytes()));
        assertNotNull(modelList);
        assertEquals(2, modelList.size());
        System.out.println(converter.convertToJson(modelList));
    }

}
